services:
  # 1. Сервис для aiogram бота
  bot:
    build: .
    container_name: buyursin_bot
    command: python main.py 
    
    env_file:
      - .env
      
    environment:
      DB_HOST: db 
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_NAME}
      
    depends_on:
      db:
        condition: service_healthy
    restart: always

  # 2. Сервис для PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: buyursin_db
    env_file:
      - .env
    volumes:
      # Сохраняем данные БД на хосте
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"] 
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
      
      
# Определяем том для сохранения данных БД
volumes:
  postgres_data: